azureIdentity:
  # enabled/disable deployment of azure identity and binding
  enabled: true
  name: "vault"
  # if not defined, then the azure identity will be deployed in the same namespace as the chart
  namespace: ""
  # type 0: MSI, type 1: Service Principal
  type: 0
  # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
  resourceID: ""
  clientID: ""

azureIdentityBinding:
  name: "azure-identity-binding"
  selector: "demo"